admin_post:
    path:     /
    defaults: { _controller: "AppBundle:VbaPost:index" }

admin_post_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:VbaPost:show" }

admin_post_new:
    path:     /new
    defaults: { _controller: "AppBundle:VbaPost:new" }

admin_post_create:
    path:     /create
    defaults: { _controller: "AppBundle:VbaPost:create" }
    methods:  POST

admin_post_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:VbaPost:edit" }

admin_post_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:VbaPost:update" }
    methods:  [POST, PUT]

admin_post_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:VbaPost:delete" }
    methods:  [POST, DELETE]
