app_admin_post:
    resource: "@AppBundle/Resources/config/routing/vbapost.yml"
    prefix:   /admin_post

app_admin_work:
    resource: "@AppBundle/Resources/config/routing/vbawork.yml"
    prefix:   /admin_work

#homepage:
#    path:     /
#    defaults: { _controller: "AppBundle:Default:index" }
   
homepage:
    path:      /{_locale}
    defaults:  { _controller: AppBundle:Default:index, _locale: en }
    requirements:
        _locale:  en|pt
        
        
post:
    path:      /{_locale}/{title}
    defaults:  { _controller: AppBundle:Default:post, _locale: en }
    requirements:
        _locale:  en|pt
    
contact:
    path:     /contact
    defaults: { _controller: "AppBundle:Default:contact" }